### ISSUE TITLE
Private key and public key are not getting created.

### ISSUE THREAD

**Issue by rejusam** [surhudm/pegasus#1]
After entering the following commands :
![Screenshot 2020-07-02 at 6 07 21 PM](https://user-images.githubusercontent.com/6176357/86322389-ff21bb00-bc8e-11ea-94f1-64f7602f5d27.png)

Unable to locate the Public and private key at 

> $HOME/.ssh/ 

![Screenshot 2020-07-02 at 6 12 48 PM](https://user-images.githubusercontent.com/6176357/86322791-b0c0ec00-bc8f-11ea-8d7e-322dc322ade7.png)

What could be the reason?

**Comment by Kishore96in** [comment]
I guess the key might be saved in your home directory, since you didn't enter a path at the `Enter file in which to save the key` step.
