### ISSUE TITLE
Issue with keygen

### ISSUE THREAD

**Issue by Bhaskar123-star** [surhudm/pegasus#2]
Sir,

I created keygens for ssh but there are couple of issues:

1.  Command "ssh-copy-id your_username@pegasus.ac.iucaa.in" gives error "No identities found". So I changed it to "ssh-copy-id -i keygen.pub your_username@pegasus.ac.iucaa.in". That works but I'm not sure if it is correct.

2.  When I run the command "ssh your_username@pegasus.ac.iucaa.in", ssh daemon asks for the old password not the passphrase for key.

Thanks,
Bhaskar Arya

**Comment by surhudm** [comment]
Thanks for reporting.

Once you login to pegasus (say with the password), can you see your public key in `.ssh/authorized_keys`? If not, then just put your public key in the file `.ssh/authorized_keys` on the server and try again. Please let me know what works so that I can update the methods for Windows users.

**Comment by Bhaskar123-star** [comment]
Sir,

The issue is resolved. It seems there was some misunderstanding on my part.
1. After "ssh-keygen -t rsa -b 4096 -C "your_email_address" command I was not supposed to enter any file name and simply press enter.
2.  Command  "ssh your_username@pegasus.ac.iucaa.in", is VALID and no modification is required.

Thanks for the reply and apologies for any confusion.

Bhaskar Arya

**Comment by surhudm** [comment]
Ok great! I switched to windows to test out the method and it worked perfectly fine. Sorry I will make sure I edit to make it clear to not change the location of the file, even if the filename is changed. So entering $HOME/.ssh/id_rsa2 would be ok, for example.
