### ISSUE TITLE
Using Remote Gateway - Not able to setup ssh keys

### ISSUE THREAD

**Issue by p20180014** [surhudm/pegasus#3]
When I run command (Ubuntu 19.04):
ssh-copy-id clokesh@gw-pune.iucaa.in
/usr/bin/ssh-copy-id: ERROR: No identities found

**Comment by surhudm** [comment]
You should try:

```
ssh-copy-id -i $HOME/.ssh/id_rsa.pub clokesh@gw-pune.iucaa.in
```

This assumes you have a ssh key file generated in `$HOME/.ssh/`
