### ISSUE TITLE
Can't copy files from cluster account to my local system

### ISSUE THREAD

**Issue by bhaskar-astro** [surhudm/pegasus#4]
My ssh key has been successfully installed and I can log into the cluster. But whenever I am trying to copy files from cluster to my local system I am getting following error:

(py3) -bash-4.2$ scp filename username@ip-address:~/
Warning: Permanently added 'ip-address' (ECDSA) to the list of known hosts.
Permission denied (publickey,password).
lost connection

However if I try to copy files from cluster to my local system using the terminal of my local system it's working. Commands are here:

scp  username@pegasus.ac.iucaa.in:full-address-to-the-file address-of-local-system

I don't understand what's going on here. I would appreciate if you can address how to copy files using the first method.

**Comment by surhud** [comment]
Hi, can you please post the exact output from the terminal and the exact commands you entered in the terminal?

**Comment by surhud** [comment]
Ahh, sorry for not reading the message correctly. Do you have a ssh server on your machine, and if so, is it setup correctly to also accept ssh keys? It is less of a cluster configuration issue, than an issue with your local system's ssh server. Please paste entries from your /var/log/secure or /var/log/auth where the corresponding sshd entries will be logged when the permission is denied.
